// Copyright © YanivZeg <https://github.com/YanivZeg>
// SPDX-License-Identifier: MIT

export global ImGuiAdapter {
    callback forward-pointer-event(PointerEvent, length, length);
    callback forward-scroll-event(PointerScrollEvent) -> EventResult;
    callback forward-key-pressed-event(KeyEvent) -> EventResult;
    callback forward-key-released-event(KeyEvent) -> EventResult;
    callback forward-focus-changed-event(FocusReason);
}

export component ImGui inherits Rectangle {
    in property <image> texture;

    image := Image {
        source: root.texture;
        width: 100%;
        height: 100%;
    }

    ta := TouchArea {
        pointer-event(e) => { ImGuiAdapter.forward-pointer-event(e, self.mouse-x, self.mouse-y) }
        scroll-event(e) => { ImGuiAdapter.forward-scroll-event(e) }
    }

    fs := FocusScope {
        capture-key-pressed(e) => { ImGuiAdapter.forward-key-pressed-event(e) }
        capture-key-released(e) => { ImGuiAdapter.forward-key-released-event(e) }
        focus-changed-event(e) => { ImGuiAdapter.forward-focus-changed-event(e) }
    }
}