// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Slider, GroupBox, HorizontalBox, VerticalBox, GridBox } from "std-widgets.slint";

export global ImGuiAdapter {
    callback forward-pointer-event(PointerEvent, length, length);
    callback forward-scroll-event(PointerScrollEvent) -> EventResult;
    callback forward-key-pressed-event(KeyEvent) -> EventResult;
    callback forward-key-released-event(KeyEvent) -> EventResult;
    callback forward-focus-changed-event(FocusReason);
}

component ImGui inherits Rectangle {
    in property <image> texture;

    image := Image {
        source: root.texture;
        width: 100%;
        height: 100%;
    }

    ta := TouchArea {
        pointer-event(e) => { ImGuiAdapter.forward-pointer-event(e, self.mouse-x, self.mouse-y) }
        scroll-event(e) => { ImGuiAdapter.forward-scroll-event(e) }
    }

    fs := FocusScope {
        capture-key-pressed(e) => { ImGuiAdapter.forward-key-pressed-event(e) }
        capture-key-released(e) => { ImGuiAdapter.forward-key-released-event(e) }
        focus-changed-event(e) => { ImGuiAdapter.forward-focus-changed-event(e) }
    }
}

export component App inherits Window {
    in property <image> texture <=> imgui.texture;
    out property <int> requested-texture-width: imgui.width/1phx;
    out property <int> requested-texture-height: imgui.height/1phx;
    out property <float> selected-red <=> red.value;
    out property <float> selected-green <=> green.value;
    out property <float> selected-blue <=> blue.value;

    preferred-width: 600px;
    preferred-height: 600px;
    title: "Slint OpenGL Texture Example";
    // icon: @image-url("../../logo/slint-logo-small-light.png");

    VerticalBox {
        Text {
            text: "This text is rendered using Slint. The ImGui scene below is rendered into an OpenGL texture.";
            wrap: word-wrap;
        }

        imgui := ImGui {
            preferred-width: 640px;
            preferred-height: 640px;
            min-width: 64px;
            min-height: 64px;
            width: 100%;
            //height: 100%;
        }

        GroupBox {
            title: "Cube Color Controls";

            GridBox {
                Row {
                    Text {
                        text: "Red:";
                        vertical-alignment: center;
                    }

                    red := Slider {
                        minimum: 0.0;
                        maximum: 1.0;
                        value: 0.2;
                    }
                }

                Row {
                    Text {
                        text: "Green:";
                        vertical-alignment: center;
                    }

                    green := Slider {
                        minimum: 0.0;
                        maximum: 1.0;
                        value: 0.5;
                    }
                }

                Row {
                    Text {
                        text: "Blue:";
                        vertical-alignment: center;
                    }

                    blue := Slider {
                        minimum: 0.0;
                        maximum: 1.0;
                        value: 0.9;
                    }
                }
            }
        }
    }
}
